spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST} # 실제 서버용 Redis 주소
      port: 6379
    mongodb:
      uri: ${MONGO_DB_URI}

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    s3:
      # endpoint 설정 없음 -> 자동으로 S3로 접속
      bucket: ${BUCKET_NAME} # 실제 S3 버킷명으로 변경 필요
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false